### PR TITLE
Update read.me file

### PR DESCRIPTION
**Pull request by BegzhanMaxamatxanov**
Screenshot 2024-11-09 at 15 33 29
Screenshot 2024-11-09 at 15 33 20
just fix mistakes

### CODE REVIEW

**Review by Ramadan1011 — APPROVED** [review]
good

**Review by jamshidbek7375 — APPROVED** [review]
Good. It would be nice if you could add a picture of your work

**Review by davron41 — APPROVED** [review]
Looks good!

**Comment by BegzhanMaxamatxanov** [comment]
After:
Screenshot 2024-11-09 at 15 33 29
Screenshot 2024-11-09 at 15 33 20

**Review by davron41 — CHANGES_REQUESTED** [review]
please add more detailed instruction on configuration updates for local environment.

**Pull request closed without merging**
